# Default configuration
#   org: default organization for components

[default]
org = "ssh://git@github.com/shilei-massclouds"

# Functional components list
# Style 1 - short path
#   component-name = "repo-name"
# It means: component is in the repo ("default.org/repo-name")
#
# Style 2 - full path
#   component-name = "full-repo-url"
# E.g., foo = "ssh://git@github.com/org_foo/repo_foo"

[mod_list]
boot = "boot"
config = "config"
earlycon = "earlycon"

# Root components list
# Styles are just as [mod_list]
[root_list]
rt_earlycon = "earlycon"
